//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Williwaw.Gameplay/CustomMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CustomMovement: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CustomMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CustomMovement"",
    ""maps"": [
        {
            ""name"": ""MainMov"",
            ""id"": ""7eec4b86-2aba-49b8-9322-9302e8a50fb0"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""5d8eb9b7-8672-4949-9c96-d50917175bc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""991637f2-822d-4e97-8ef3-58406945077b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainMov
        m_MainMov = asset.FindActionMap("MainMov", throwIfNotFound: true);
        m_MainMov_Walk = m_MainMov.FindAction("Walk", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainMov
    private readonly InputActionMap m_MainMov;
    private List<IMainMovActions> m_MainMovActionsCallbackInterfaces = new List<IMainMovActions>();
    private readonly InputAction m_MainMov_Walk;
    public struct MainMovActions
    {
        private @CustomMovement m_Wrapper;
        public MainMovActions(@CustomMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_MainMov_Walk;
        public InputActionMap Get() { return m_Wrapper.m_MainMov; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMovActions set) { return set.Get(); }
        public void AddCallbacks(IMainMovActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMovActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMovActionsCallbackInterfaces.Add(instance);
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
        }

        private void UnregisterCallbacks(IMainMovActions instance)
        {
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
        }

        public void RemoveCallbacks(IMainMovActions instance)
        {
            if (m_Wrapper.m_MainMovActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMovActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMovActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMovActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMovActions @MainMov => new MainMovActions(this);
    public interface IMainMovActions
    {
        void OnWalk(InputAction.CallbackContext context);
    }
}
